version: 2
updates:
- package-ecosystem: npm
  directory: "/places/"
  schedule:
    interval: "cron
    cronjob: 0 9 3 * *
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 20
  assignees:
    - mjwsteenbergen
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
- package-ecosystem: "devcontainers" # See documentation for possible values
  directory: "/"
  schedule:
    interval: "cron
    cronjob: 0 9 3 * *
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 20
  assignees:
    - mjwsteenbergen
- package-ecosystem: "github-actions"
  # Workflow files stored in the default location of `.github/workflows`
  # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
  directory: "/"
  schedule:
    interval: "cron
    cronjob: 0 9 3 * *
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 20
  assignees:
    - mjwsteenbergen
